project:
  type: website
  output-dir: docs
  pre-render:
    - python ./scripts/generate_trees_from_epicollect.py
    - python ./scripts/generate_tree_list.py
    - python ./scripts/generate_recent_trees.py
    - python ./scripts/generate_articles_from_bib.py
    - python ./scripts/generate_reports_index.py
    - python ./scripts/render_articles_to_pdf.py --output-dir docs/assets/pdfs
    - python ./scripts/clean_pdfs.py --pattern "docs/assets/pdfs/*.pdf" --inplace --no-backup
website:
  title: "Urban Research Stations<br><span style='font-size: x-small;'>at the Natural History Museum</span>"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Studies
        menu:
          - href: case-studies.qmd
      - text: Trees
        menu:
            - href: trees/index.qmd
            - href: trees/family/index.qmd
            - href: trees/genus/index2.qmd
            - href: trees/genus/index.qmd
      - text: Publications
        menu:
          - href: articles.qmd
            text: Articles
          - href: reports.qmd
            text: Urban Research Station Reports
      - team.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true
