project:
  type: website
  output-dir: docs

website:
  title: "Urban Research Station<br><span style='font-size: x-small;'>at the Natural History Museum</span>"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Studies
        menu:
          - href: case-studies.qmd
          - href: trees/index.qmd
      - text: Publications
        menu:
          - href: publications.qmd
            text: Articles
          - href: reports.qmd
            text: Urban Research Station Reports
      - team.qmd

render:
  before:
    - python ./scripts/generate_tree_list.py

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true




