"""Generate articles.qmd from assets/data/publications.bib

This script parses the BibTeX file and emits a Quarto .qmd file

Usage:
    python scripts/generate_articles_from_bib.py

    Should be called automatically on Quarto Render via _quarto.yml
"""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BIB = ROOT / "assets" / "data" / "publications.bib"
OUT = ROOT / "articles.qmd"
PUB_SRC = ROOT / "publications.qmd"


def parse_bib(text):
    entries = []
    pattern = re.compile(r"@(?P<type>\w+)\{(?P<key>[^,]+),(?P<body>.*?)\n\}\s*", re.S)
    field_re = re.compile(r"(?P<name>\w+)\s*=\s*\{(?P<value>.*?)\}\s*,?", re.S)
    for m in pattern.finditer(text):
        fields = {fm.group("name").lower(): fm.group("value").strip()
                  for fm in field_re.finditer(m.group("body"))}
        entries.append({"ENTRYTYPE": m.group("type").strip().lower(), 
                       "ID": m.group("key").strip(), **fields})
    return entries


def load_bib(path):
    return parse_bib(path.read_text(encoding="utf8"))


def format_authors(author_field):
    if not author_field:
        return ""
    return ", ".join(a.strip() for a in re.split(r"\s+and\s+|,\s*(?=[A-Z]\.?)", author_field) if a.strip())


def title_link(entry):
    title = entry.get("title", "").strip()
    if file := entry.get("file"):
        return f"[{title}]({file})"
    if url := (entry.get("url") or entry.get("doi")):
        return f"[{title}]({url})"
    return title


def venue_line(entry):
    if journal := (entry.get("journal") or entry.get("howpublished") or entry.get("type") or ""):
        return f"*{journal}*"
    return ""


def generate_qmd(entries):
    # group by year descending
    by_year = {}
    for e in entries:
        by_year.setdefault(e.get("year", "n.d."), []).append(e)

    years = sorted(by_year.keys(), reverse=True)
    recent_years = [y for y in years if y.isdigit() and int(y) >= 2025]
    wildlife_garden_years = [y for y in years if y.isdigit() and int(y) < 2025]

    lines = [
        "---",
        'title: "Articles"',
        "toc: true",
        "toc-depth: 2",
        "---\n",
        "<!-- This file is generated by scripts/generate_articles_from_bib.py. Do not edit this file directly; update the generator or the underlying data sources instead. -->",
        ""
    ]

    article_counter = 1

    # Emit recent years first
    for y in recent_years:
        lines.append(f"## {y}\n")
        for e in by_year[y]:
            if title := title_link(e):
                lines.append(f"{article_counter}. {title}")
                article_counter += 1
            if authors := format_authors(e.get("author", "")):
                lines.append("<br>" + authors)
            if venue := venue_line(e):
                lines.append("<br>" + venue)
            lines.append("")

    # Emit Wildlife Gardens Publications block
    if wildlife_garden_years:
        lines.extend([
            "# Wildlife Gardens Publications\n",
            "Papers below this point relate to research done in the NHM Wildlife Garden before the transition to the Nature Discovery Garden.",
            ""
        ])
        for y in sorted(wildlife_garden_years, reverse=True):
            lines.append(f"## {y}\n")
            for e in by_year[y]:
                if title := title_link(e):
                    lines.append(f"{article_counter}. {title}")
                    article_counter += 1
                if authors := format_authors(e.get("author", "")):
                    lines.append("<br>" + authors)
                if venue := venue_line(e):
                    lines.append("<br>" + venue)
                lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    if not BIB.exists():
        print("BibTeX file not found:", BIB)
        raise SystemExit(1)
    entries = load_bib(BIB)
    qmd = generate_qmd(entries)
    OUT.write_text(qmd, encoding="utf8")
    print("Wrote", OUT)
