"""Generate articles.qmd from assets/data/publications.bib

This script parses the BibTeX file and emits a Quarto .qmd file

Usage:
    python scripts/generate_articles_from_bib.py

    Should be called automatically on Quarto Render via _quarto.yml
"""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BIB = ROOT / "assets" / "data" / "publications.bib"
OUT = ROOT / "articles.qmd"
PUB_SRC = ROOT / "publications.qmd"


def parse_bib(text):
    entries = []
    pattern = re.compile(r"@(?P<type>\w+)\{(?P<key>[^,]+),(?P<body>.*?)\n\}\s*", re.S)
    field_re = re.compile(r"(?P<name>\w+)\s*=\s*\{(?P<value>.*?)\}\s*,?", re.S)
    for m in pattern.finditer(text):
        t = m.group("type").strip()
        key = m.group("key").strip()
        body = m.group("body")
        fields = {}
        for fm in field_re.finditer(body):
            name = fm.group("name").lower()
            val = fm.group("value").strip()
            fields[name] = val
        entries.append({"ENTRYTYPE": t.lower(), "ID": key, **fields})
    return entries


def load_bib(path):
    text = path.read_text(encoding="utf8")
    return parse_bib(text)


def format_authors(author_field):
    if not author_field:
        return ""
    # authors in BibTeX often use ' and ' or ' and, ' or commas; here authors use 'and' separated
    authors = [
        a.strip()
        for a in re.split(r"\s+and\s+|,\s*(?=[A-Z]\.?)", author_field)
        if a.strip()
    ]
    return ", ".join(authors)


def title_link(entry):
    title = entry.get("title", "").strip()
    url = entry.get("url") or entry.get("doi")
    file = entry.get("file")
    if file:
        # make a local link
        return f"[{title}]({file})"
    if url:
        return f"[{title}]({url})"
    return title


def venue_line(entry):
    journal = (
        entry.get("journal") or entry.get("howpublished") or entry.get("type") or ""
    )
    if journal:
        return f"*{journal}*"
    return ""


def generate_qmd(entries):
    # group by year descending
    by_year = {}
    for e in entries:
        year = e.get("year", "n.d.")
        by_year.setdefault(year, []).append(e)

    years = sorted(by_year.keys(), reverse=True)

    # Group all years earlier than 2025 under the Wildlife Gardens
    # Publications heading.
    wildlife_garden_block = (
        "# Wildlife Gardens Publications\n\n"
        "Papers below this point relate to research done in the NHM Wildlife Garden before the transition to the Nature Discovery Garden."
    )
    wildlife_garden_years = []
    # determine wildlife_garden_years as years < 2025 present in our entries
    for y in years:
        try:
            if int(y) < 2025:
                wildlife_garden_years.append(y)
        except Exception:
            pass

    lines = []
    lines.append("---")
    lines.append('title: "Articles"')
    lines.append("toc: true")
    lines.append("toc-depth: 2")
    lines.append("---\n")
    # advisory comment for developers: generated file warning
    lines.append(
        "<!-- This file is generated by scripts/generate_articles_from_bib.py. Do not edit this file directly; update the generator or the underlying data sources instead. -->"
    )
    lines.append("")

    # Split years into recent (>=2025) and wildlife (<2025)
    recent_years = [y for y in years if (y.isdigit() and int(y) >= 2025)]
    wildlife_garden_years = [y for y in years if (y.isdigit() and int(y) < 2025)]

    # global article counter (sequential across the whole document)
    article_counter = 1

    # Emit recent years first
    for y in recent_years:
        lines.append(f"## {y}\n")
        for e in by_year[y]:
            title = title_link(e)
            authors = format_authors(e.get("author", ""))
            venue = venue_line(e)
            if title:
                # prefix the title with a sequential article number
                lines.append(f"{article_counter}. {title}")
                article_counter += 1
            if authors:
                lines.append("<br>" + authors)
            if venue:
                lines.append("<br>" + venue)
            lines.append("")

    # Emit Wildlife Gardens Publications block and then all wildlife years
    if wildlife_garden_years:
        if wildlife_garden_block:
            lines.append(wildlife_garden_block)
            lines.append("")
        else:
            lines.append("# Wildlife Gardens Publications\n")
        for y in sorted(wildlife_garden_years, reverse=True):
            lines.append(f"## {y}\n")
            for e in by_year[y]:
                title = title_link(e)
                authors = format_authors(e.get("author", ""))
                venue = venue_line(e)
                if title:
                    # prefix the title with a sequential article number
                    lines.append(f"{article_counter}. {title}")
                    article_counter += 1
                if authors:
                    lines.append("<br>" + authors)
                if venue:
                    lines.append("<br>" + venue)
                lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    if not BIB.exists():
        print("BibTeX file not found:", BIB)
        raise SystemExit(1)
    entries = load_bib(BIB)
    qmd = generate_qmd(entries)
    OUT.write_text(qmd, encoding="utf8")
    print("Wrote", OUT)
